- hosts: target
  vars_files:
    - ../vars.yml
  tasks:
    - name: install prerequisites
      action: apt pkg={{item}} state=latest
      with_items:
        - python-psycopg2
        - python-dev
        - postgresql
        - postgresql-server-dev-10
- hosts: target
  vars_files:
    - ../vars.yml
  become: yes
  become_user: postgres
  tasks:
    - name: setup db
      action: postgresql_db name=sentry
    - name: setup user
      action: postgresql_user name=sentry password=sentry db=sentry priv=ALL role_attr_flags=SUPERUSER encrypted=yes
  handlers:
    - include: handlers.yml
  
